#started from: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# This workflow will do a clean installation of node dependencies, cache/restore them,
  #(not anymore: build the source code and run tests across different versions of node)
# package the minified browser bundle under docs/src
# and then push it to the web-editor: commit and push to main, this will trigger the deployment to that repository's GItHubPages automatically

name: Publish to WebEditor

on:
  push:
    branches: [ "40-automate-deployment-to-web-editor" ] #main
  pull_request:
    branches: [ "40-automate-deployment-to-web-editor" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test
    - run: npm exec ng run keml.graphical:package
    #now, minified version lies under dist/src
    - run: echo $(cat ./dist/src/index.html)   #test that srcs are generated
#************** interact with the web-editor repository *****************
    - name: Set up Git repository to push
      uses: actions/checkout@v4
      with:
        repository: keml-group/web-editor
        ref: main
        path: webeditor
        token: ${{secrets.WEB_EDITOR_ACCESS}}
    - run: cp -r ./dist/src ./webeditor/src
    - name: Add and commit to main
      run: |
        cd webeditor
        git config --global user.name 'publish-bot'
        git config --global user.email 'publish-bot@keml-group.github.io'
        git add src
        git commit -m "[Bot] Update from main"
        git push
    - run: echo $( ls )
