#started from: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# This workflow will do a clean installation of node dependencies, cache/restore them,
  #(not anymore: build the source code and run tests across different versions of node)
# package the minified browser bundle under dist/src
# and then push it to the web-editor: commit and push to main, this will trigger the deployment to that repository's GItHubPages automatically

name: Push to WebEditor (except Publish)

on:
  push:
    branches-ignore: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Necessary to access local action
      - name: real call to build
        uses: ./.github/actions/buildAndPackage
